---

- name: Install curl
  package:
    name: curl
    state: installed

- name: Add Jenkins repo
  yum_repository:
    name: jenkins
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgkey: http://pkg.jenkins.io/redhat/jenkins.io.key
    description: Jenkins official repo
    gpgcheck: yes

- name: Install Jenkins
  package:
    name: jenkins
    state: present
  notify: Create admin users

- name: Create /etc/sysconfig/jenkins
  template:
    src: RedHat/sysconfig.jenkins.j2
    dest: /etc/sysconfig/jenkins
    validate: sh -n %s
  notify: Restart jenkins

- name: Enable Jenkins
  service:
    name: "{{ jenkins_master_service }}"
    enabled: yes

- name: Install openssl
  yum:
    name: openssl
    state: present
