---
- src: mashimom.jenkins_role
- src: sergeyhush.jenkins
- src: crossgovernmentservices.jenkins
- src: courtlandj.jenkins
- src: dhs-shine.jenkins
- src: ohtomi.jenkins2
- src: binarytemple.jenkins
- src: Ochir.jenkins_centos
- src: votum.jenkins
- src: bastly.jenkins
- src: acceleanu.jenkins
- src: virtualenv.jenkins
- src: v0rts.jenkins
- src: forsingh.jenkins
- src: TuxOtaku.jenkins
- src: blburns.jenkins
- src: raguilera82.jenkins
- src: ChristopherDavenport.jenkins
- src: jhammell.jenkins
- src: geerlingguy.jenkins
- src: goozbach.jenkins
- src: junaid18183.jenkins
- src: alexagranov.jenkins-oracle-java
- src: AsianChris.jenkins
- src: medzin.jenkins
- src: marcelocorreia.jenkins2
- src: oclaussen.ansible-role-jenkins
- src: sansible.jenkins_server
- src: idealista.jenkins-role
- src: EncoreTechnologies.ansible-role-jenkins
- src: pgporada.jenkins
- src: aldavud.ansible-role-jenkins2
- src: shomatan.jenkins
- src: waltervargas.ansible-role-jenkins
- src: entercloudsuite.jenkins
- src: repleo.jenkins
- src: pkorobeinikov.jenkins
- src: grlee.jenkins_ubuntu
- src: resmo.jenkins
- src: jackl0phty.ansible-role-jenkins
- src: ykhrustalev.jenkins
- src: exolink.ansible-role-jenkins
- src: wtanaka.jenkins
- src: davenport-ans.ansible-role-jenkins
- src: leifmadsen.ansible-role-jenkins
- src: juju4.ansible-role-jenkins
- src: olo-dw.ansible-role-jenkins
- src: akry.jenkins
- src: plone.plone_jenkins_server
- src: goozbach.jenkins-perl
- src: avanov.jenkins
- src: jeqo.jenkins
- src: tersmitten.jenkins
- src: ChristopherDavenport.jenkins-slave
- src: reallyenglish.jenkins-slave
- src: ccollicutt.jenkins
- src: reallyenglish.jenkins-master
- src: suzuki-shunsuke.jenkins-centos
- src: suzuki-shunsuke.jenkins-ubuntu
- src: FGtatsuro.jenkins
- src: openstack.jenkins
- src: kei-yamazaki.jenkins
- src: colstrom.jenkins
- src: bersace.jenkins-epo
- src: erjac77.jenkins
- src: pablerass.jenkins
- src: reynn.jenkins-swarm
- src: juju4.jenkins
- src: avinash6784.jenkins
- src: novafloss.jenkins-node
- src: mrlesmithjr.jenkins
- src: goozbach.jenkins-git
- src: alban.andrieu.jenkins-slave
- src: yauh.jenkins
- src: novafloss.jenkins-ghp
- src: fdupoux.jenkins
- src: fatal-exception.jenkins
- src: haos616.docker-jenkins
- src: wurbanski.jenkins-swarm-agent
- src: trombik.ansible-role-jenkins-slave
- src: wunzeco.jenkins
- src: alban.andrieu.jenkins-swarm
- src: azavea.jenkins
- src: GielDeBleser.Ansible-Jenkins-Maven
- src: kobanyan.jenkins-jnlp-slave
- src: HanXHX.jenkins-php
- src: SoInteractive.jenkins
- src: NINEJKH.jenkins
- src: wikivoks.jenkins-swarm-slave
- src: clayman74.jenkins
- src: trombik.ansible-role-jenkins-master
- src: SyedMuhammadSufyian.jenkins
- src: nosherwanijaz.jenkins
- src: plone.plone_jenkins_node
- src: demoglot.jenkins
- src: Stouts.jenkins
- src: jtyr.jenkins_master
- src: Azulinho.azulinho-jenkins-plugins
- src: yauh.jenkins-php
- src: emmetog.jenkins
- src: AAROC.CODE-RADE-jenkins-role
- src: stevehouel.jenkins-role
- src: ThePrudents.jenkins2
- src: juju4.ansible-jenkinsenv
- src: flyapen.jenkins
- src: bronzdoc.jenkins-docker-service
- src: infOpen.jenkins
- src: novafloss.jenkins-api
- src: Azulinho.azulinho-jenkins-server
- src: Azulinho.azulinho-jenkins-kick-pipelines
- src: jtyr.jenkins_slave
- src: vamsi8977.jenkins-shravan
- src: karlmdavis.jenkins2
- src: REI-Systems.jenkins
- src: awasilyev.jenkins-container
- src: ThirteenLtda.autoproj-jenkins
- src: pablerass.jenkins-slave-linux
- src: pablerass.jenkins-slave-windows
- src: hoall.jenkins
- src: doudou.autoproj-jenkins
- src: peopledoc.ansible-role-jenkins-node
- src: therelaxist.ans-role-jenkins
- src: bishopbm1.ansible-features
- src: vamsi8977.solita.jenkins
- src: Azulinho.azulinho-jenkins-reconfigure-jobs-using-job-builder
- src: shelleg.juseppe
- src: Azulinho.azulinho-yum-repo-jenkins
- src: Azulinho.azulinho-jenkins-reconfigure-jobs-using-jinja2
- src: Azulinho.azulinho-jenkins-reconfigure-jobs-using-job-dsl
- src: softasap.sa-box-jenkins
- src: RealSalmon.jenkins-master
- src: whirm.jenkins_slavee
- src: wunzeco.jenkins-extra
- src: Azulinho.azulinho-jenkins-job-builder
- src: Azulinho.azulinho-jenkins-fully-baked
- src: radamanth.jenkins-ansible
- src: mmagonde.jenkins-swarm
- src: capitanh.jenkins-ansible-role
- src: kaguxmail.Stouts_jenkins
