---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install -r requirements.txt
        - ansible-galaxy install -r role_requirements.yml
        - bundle install
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container ${IMAGE_NAME} /bin/sh
      after_script:
        - docker rm -f container
      env:
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:debian-jessie
        - TARGET=container
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container ${IMAGE_NAME} /bin/sh
      after_script:
        - docker rm -f container
      env:
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:alpine-3.3
        - TARGET=container

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - pip install -r requirements.txt
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install -r role_requirements.yml
  - bundle install

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} -vvvv
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
