---
  -  name: Installing Jenkins ..
     apt-get:
        name: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.89.3_all.deb
        state: present

  -  name: Ensure Jenkins service should be started
     service: name=jenkins state:started
