---

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
      update_cache: yes

  - name: Add Jenkins apt repository key.
    apt_key:
      url: deb https://pkg.jenkins.io/debian-stable binary/
      state: present

  - name: Installing jenkins
    apt:
      name: jenkins-{{jenkins_version_debian}}
      update_cache: yes
      state: present
