---

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: https://pkg.jenkins.io/debian-stable
      state: present
      update_cache: yes

  - name: Add Jenkins apt repository key.
    apt_key:
      url:  https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: Installing jenkins
    apt:
      name: jenkins
      state: present
